export const config = [
    { "name": "Floorp", "image": "PYqI2g1.png", "release": "2021", "company": "Ablaze", "source": "Open" },
    { "name": "Arc", "image": "j5UlMsQ.png", "release": "25 July, 2023", "company": "The Browser Company", "source": "Closed" },
    { "name": "IceDragon", "image": "XkMobrA.png", "release": "June 19, 2019", "company": "Comodo", "source": "Open" },
    { "name": "Firefox", "image": "DjNiwAR.png", "release": "November 9, 2004", "company": "Mozilla", "source": "Open" },
    { "name": "Midori", "image": "kNj7Fzk.png", "release": "December 16, 2007", "company": "Midori", "source": "Open" },
    { "name": "DuckDuckGo", "image": "DzDRyys.png", "release": "April 2022", "company": "DuckDuckGo", "source": "Closed" },
    { "name": "Chrome", "image": "lT0KeNbZ.png", "release": "September 2, 2008", "company": "Google", "source": "Closed" },
    { "name": "Chromium", "image": "NFS7svu.png", "release": "2 September 2008", "company": "Google", "source": "Open" },
    { "name": "Brave", "image": "VjF0Xzk.png", "release": "13 November 2019", "company": "Brave Software", "source": "Open" },
    { "name": "Edge", "image": "nNJ5Uwe.png", "release": "April 29, 2015", "company": "Microsoft", "source": "Closed" }, 
    { "name": "Waterfox", "image": "Hd4wOQD.png", "release": "27 March 2011", "company": "System1", "source": "Open" },
    { "name": "Yandex", "image": "xpZ0tXh.png", "release": "1 October 2012", "company": "Yandex", "source": "Closed" },
    { "name": "Netscape", "image": "mq3t51c.png", "release": "15 December 1994", "company": "Netscape", "source": "Closed" },
    { "name": "Internet Explorer", "image": "U3YGsG3.png", "release": "August 24, 1995", "company": "Microsoft", "source": "Closed" },
    { "name": "Safari", "image": "5KMwIsn.png", "release": "January 7, 2003", "company": "Apple", "source": "Closed" },
    { "name": "Tor", "image": "FJMXNMC.png", "release": "20 September 2002", "company": "Tor Project", "source": "Open" },
    { "name": "Opera GX", "image": "KBPxrvp.png", "release": "June 11, 2019", "company": "Opera", "source": "Closed" },
    { "name": "Opera", "image": "kiaPlrm.png", "release": "April 10, 1995", "company": "Opera", "source": "Closed" },
    { "name": "Vivaldi", "image": "Hy2uKff.png", "release": "April 6, 2016", "company": "Vivaldi Technologies", "source": "Closed" },
    { "name": "Otter Browser", "image": "6I3UYjm.png", "release": "January 1, 2014", "company": "Otter Browser", "source": "Open" },
    { "name": "Samsung Internet", "image": "wnK8RU8.png", "release": "2015", "company": "Samsung", "source": "Closed" },
    { "name": "Blisk", "image": "15Qy0zn.png", "release": "October 2022", "company": "Blisk", "source": "Closed" },
    { "name": "Silk", "image": "llCeNqm.png", "release": "November 15, 2011", "company": "Amazon", "source": "Closed" },
    { "name": "SeaMonkey", "image": "vb6TtqD.png", "release": "January 30, 2006", "company": "SeaMonkey Council", "source": "Open" },
    { "name": "Epic Browser", "image": "HJe6Vw2.png", "release": "July 15, 2010", "company": "Hidden Reflex", "source": "Closed" },
    { "name": "Avast Secure Browser", "image": "kkPgBET.png", "release": "2016", "company": "Avast Software", "source": "Closed" },
    { "name": "Zen Browser", "image": "lWcrWkt6.png", "release": "Jul 7, 2024", "company": "Zen Browser", "source": "Open" },
    { "name": "ChatGPT Atlas", "image": "AYaofv4o.png", "release": "October 21, 2025", "company": "OpenAI", "source": "Closed" },
    { "name": "Comet", "image": "ryYhP6aV.png", "release": "July 9, 2025", "company": "Perplexity", "source": "Closed" },
    { "name": "Helium", "image": "wNC24bkJ.png", "release": "Aug 18, 2025", "company": "InputNet", "source": "Open" }
]